In [40]:
import numpy as np 
import pandas as pd

In [41]:
data = {
    'Name' : ['john','Anna','shreya','linger'],
    'Age': [28,34,29,42],
    'City': ['Newyork','Mumbai','paris','London'],
    'salary':[ 65000,45000,68000,85000]
    
}
df = pd.DataFrame(data)
df

     Name  Age     City  salary
0    john   28  Newyork   65000
1    Anna   34   Mumbai   45000
2  shreya   29    paris   68000
3  linger   42   London   85000

In [42]:
df

     Name  Age     City  salary
0    john   28  Newyork   65000
1    Anna   34   Mumbai   45000
2  shreya   29    paris   68000
3  linger   42   London   85000

In [43]:
data_list = [
     ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [44]:
df2 = pd.DataFrame(data_list)
columns = [ "Name", " age"," city","salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name   age      city  salary
0   John    28  New York   65000
1   Anna    34     Paris   70000
2  Peter    29    Berlin   62000
3  Linda    42    London   85000

In [45]:
df2

    Name   age      city  salary
0   John    28  New York   65000
1   Anna    34     Paris   70000
2  Peter    29    Berlin   62000
3  Linda    42    London   85000

In [46]:
print(df.columns)

Index(['Name', 'Age', 'City', 'salary'], dtype='str')

In [47]:
df2 = df[['Name','Age']]
df2

     Name  Age
0    john   28
1    Anna   34
2  shreya   29
3  linger   42

In [48]:
df2['Designation'] = ['Doctor','ENG','Teacher','Doctor']

In [49]:
df2

     Name  Age Designation
0    john   28      Doctor
1    Anna   34         ENG
2  shreya   29     Teacher
3  linger   42      Doctor

In [50]:
data_list = [
     ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [51]:
df3 = pd.DataFrame(data_list)
df3 = pd.DataFrame(data_list)
df3

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [52]:
df3[1]

0    28
1    34
2    29
3    42
Name: 1, dtype: int64

In [53]:
df3[4]=['doctor','teacher','sales','eng']

In [54]:
df3

       0   1         2      3        4
0   John  28  New York  65000   doctor
1   Anna  34     Paris  70000  teacher
2  Peter  29    Berlin  62000    sales
3  Linda  42    London  85000      eng

In [58]:
df3.drop(4, axis = 1)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [59]:
df3.loc[[1,2]]

       0   1       2      3        4
1   Anna  34   Paris  70000  teacher
2  Peter  29  Berlin  62000    sales

In [62]:
df3.loc[[0,1]][[2,3]]

          2      3
0  New York  65000
1     Paris  70000

In [ ]:
# conditional statements

In [71]:
df

     Name  Age     City  salary
0    john   28  Newyork   65000
1    Anna   34   Mumbai   45000
2  shreya   29    paris   68000
3  linger   42   London   85000

In [72]:
# I Only want to see those people whose age is above > 30

In [73]:
df[df["Age"] > 30]

     Name  Age    City  salary
1    Anna   34  Mumbai   45000
3  linger   42  London   85000

In [74]:
# I only want to see those people whose age is above > 30 and their city must be paris

In [78]:
df[(df['Age'] > 30) & (df['City'] == 'Mumbai')]

   Name  Age    City  salary
1  Anna   34  Mumbai   45000