In [11]:
import numpy as np 
import pandas as pd

In [12]:
#finding Missing Data

In [13]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [18]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# Removing Missing data

In [19]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [20]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [22]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
#Filling the missing data

In [23]:
df.fillna("kirti")

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  kirti
2  kirti  3    3.0  kirti
3    4.0  4  kirti  kirti
4    5.0  5  kirti    5.0

In [25]:
values ={'A': 0,'B': 400,'C':456,'D': "kirti"}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  kirti
2  0.0  3    3.0  kirti
3  4.0  4  456.0  kirti
4  5.0  5  456.0    5.0

In [26]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0